akeneo/MagentoConnectorBundle

Writer/AttributeWriter.php
=> Remove "@return void".

Reader/CategoryReader.php, Resources/config/batch_jobs.yml, Resources/config/readers.yml
| Fixed tickets        | MC-85
=> MC-85: Add a category reader which filter by channel and rm root from selection

Normalizer/CategoryNormalizer.php, Normalizer/Dictionary/CategoryLabelDictionary.php, Processor/CategoryToArrayProcessor.php, Resources/config/batch_jobs.yml, Resources/config/processors.yml, Resources/config/serializers.yml
| Fixed tickets        | MC-85
=> MC-85: Add category processor, normalizer and dictionary

Resources/config/batch_jobs.yml, Resources/config/writers.yml, Webservice/MagentoSoapClient.php, Writer/AbstractWriter.php, Writer/CategoryWriter.php, Writer/ProductWriter.php
| Fixed tickets        | MC-85
=> MC-85: Allows to send categories and manage errors

Webservice/MagentoSoapClient.php
Bug fix: [no]
Feature addition: [yes]
Checkstyle issues: [no]*
=> MC-140: Add more information on error from the Magento Connector.

DependencyInjection/Compiler/SerializerPass.php, Normalizer/ProductNormalizer.php, Normalizer/ProductValueNormalizer.php, Processor/CategoryToArrayProcessor.php, Reader/FamilyReader.php, Resources/config/helpers.yml, Resources/config/processors.yml, Resources/config/readers.yml, Resources/config/serializers.yml, Resources/config/webservices.yml, Resources/config/writers.yml, Writer/AbstractWriter.php
=> Clean branch

Normalizer/CategoryNormalizer.php, spec/Pim/Bundle/MagentoConnectorBundle/Normalizer/CategoryNormalizerSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Processor/CategoryToArrayProcessorSpec.php
| Fixed tickets        | MC-85
=> MC-85: Add specs

CHANGELOG.md, Cleaner/ProductCleaner.php, Normalizer/AbstractNormalizer.php, Resources/config/cleaners.yml, Resources/translations/messages.en.yml, Resources/translations/messages.fr.yml
Bug fix: [no]
Feature addition: [yes]
ChangeLog updated: [yes]
=> MC-38: Add an option to choose if products not handled by Akeneo should be deleted/disabled or not during an export.

Cleaner/CategoryCleaner.php, Cleaner/FamilyCleaner.php, Writer/AttributeWriter.php
=> MC-90: Remove silently caught exceptions

Resources/doc/troubleshooting.md, Resources/doc/userguide.md
=> MC-162: Completing documentation

composer.json
=> Fix Gedmo version in composer to be synchro with pim-dev

CHANGELOG.md, Manager/PriceMappingManager.php
Bug fix: yes
Feature addition: no
Backwards compatibility break: no
Phpspec specification passes: no
Checkstyle issues: no
ChangeLog updated: yes
Fixes the following issue: MC-165
=> [MC-165] Fix price computation problem on configurable product export

Resources/doc/userguide.md
=> MC-154: Add doc to explain how enabling the Magento SOAP profiler.

composer.json
=> Fix gedmo in composer

CHANGELOG.md, Webservice/Webservice.php
Bug fix: [yes]
Checkstyle issues: [no]*
ChangeLog updated: [yes]
=> MC-175: Prevent bug during product creation if sku is a number.

CHANGELOG.md, Normalizer/AttributeNormalizer.php
| Tests pass?          | No
| Fixed tickets        | MC-182
| DB schema updated?   |  No
=> MC-182: Remove useless attributes fields in attribute normalizer

CHANGELOG.md, Normalizer/CategoryNormalizer.php, Normalizer/ConfigurableNormalizer.php, Normalizer/ProductNormalizer.php, Processor/AbstractProductProcessor.php, Processor/ProductProcessor.php, Resources/translations/messages.en.yml, Resources/translations/messages.fr.yml, Webservice/Webservice.php
| New feature?         | Yes
| Tests pass?          | No
| Fixed tickets        | MC-171
=> MC-171: Better handling of url keys

Command/PurgeMappingCommand.php, DependencyInjection/PimMagentoConnectorExtension.php, Purger/MappingPurger.php, Resources/config/purgers.yml
Bug fix: n
Feature addition: y
Backwards compatibility break: n
Phpspec specification passes: y
Checkstyle issues: n
ChangeLog updated: n
Fixes the following issue: MC-169
=> MC-169 : Add a command to purge database of mapping

CHANGELOG.md, Webservice/Webservice.php, Writer/CategoryWriter.php
| Tests pass?          | No
| Fixed tickets        | MC-189
=> MC-189: Update product and category url keys in admin store view

Entity/DeltaProductAssociationExport.php, Manager/DeltaProductExportManager.php, Reader/ORM/DeltaProductAssociationReader.php, Resources/config/batch_jobs.yml, Resources/config/doctrine/DeltaProductAssociationExport.orm.yml, Resources/config/entities.yml, Resources/config/managers.yml, Resources/config/readers.yml, Resources/config/repositories.yml, Resources/config/writers.yml, Writer/DeltaProductAssociationWriter.php
Bug fix: n
Feature addition: y
Backwards compatibility break: n
Phpspec specification passes: y
Checkstyle issues: n
ChangeLog updated: n
Fixes the following issue: MC-180
=> MC-180 : Add delta product association export

Entity/DeltaConfigurableExport.php, Manager/DeltaConfigurableExportManager.php, Processor/DeltaConfigurableProcessor.php, Reader/ORM/DeltaConfigurableReader.php, Resources/config/batch_jobs.yml, Resources/config/doctrine/DeltaConfigurableExport.orm.yml, Resources/config/entities.yml, Resources/config/managers.yml, Resources/config/processors.yml, Resources/config/readers.yml, Resources/config/repositories.yml, Resources/config/writers.yml, Writer/DeltaConfigurableWriter.php
| Fixed tickets        | MC-181
| DB schema updated?   | y
=> MC-181 : Add delta configurable export

CHANGELOG.md, Normalizer/OptionNormalizer.php
| BC breaks?           | Perhaps
| Fixed tickets        | MC-168
=> MC-168: Refactor OptionNormalizer::getOptionLabel()

CHANGELOG.md, Manager/AttributeGroupMappingManager.php, Manager/AttributeMappingManager.php, Manager/CategoryMappingManager.php, Manager/FamilyMappingManager.php, Resources/config/doctrine/MagentoAttributeMapping.orm.yml, Resources/config/doctrine/MagentoCategoryMapping.orm.yml, Resources/config/doctrine/MagentoFamilyMapping.orm.yml, Resources/config/doctrine/MagentoGroupMapping.orm.yml, Resources/sql/mapping_migration.post_schema_update.sql, Resources/sql/mapping_migration.pre_schema_update.sql, UPGRADE.md
| Bug fix?             | yes
| New feature?         | no
| BC breaks?           | yes
| Tests pass?          | no
| Checkstyle issues?*  | no
| PMD issues?**        |
| Changelog updated?   | yes
| Fixed tickets        | MC-194
| DB schema updated?   | yes
| Migration script?    | yes
=> MC-194: Fix mapping to manage multiple magento environment on a single PIM instance

Cleaner/AttributeCleaner.php, Cleaner/CategoryCleaner.php, Cleaner/Cleaner.php, Cleaner/ConfigurableCleaner.php, Cleaner/FamilyCleaner.php, Cleaner/OptionCleaner.php, Cleaner/ProductCleaner.php, Resources/fixtures/demo_magento/jobs.yml
| Fixed tickets        | MC-202
=> MC-202: Delete validation annotation

Reader/ORM/DeltaConfigurableReader.php, Reader/ORM/DeltaProductAssociationReader.php, Reader/ORM/DeltaProductReader.php
| Fixed tickets        | MC-201
=> MC-201: Remove query part on "discr" on DeltaProductReader

CHANGELOG.md, Command/PurgeDeltaCommand.php, Command/PurgeMappingCommand.php, Purger/DeltaTablePurger.php, Purger/PurgerInterface.php, Resources/config/purgers.yml
| Changelog updated?   | y
| Fixed tickets        | MC-208
=> MC-208: Add PurgerInterface and DeltaTablePurger

Reader/ORM/CategoryReader.php
| Fixed tickets        | MC-205
=> MC-205: Add Channel in Category export

CHANGELOG.md, Manager/AttributeGroupMappingManager.php, Manager/AttributeMappingManager.php, Manager/CategoryMappingManager.php, Manager/FamilyMappingManager.php, Resources/config/doctrine/MagentoAttributeMapping.orm.yml, Resources/config/doctrine/MagentoCategoryMapping.orm.yml, Resources/config/doctrine/MagentoFamilyMapping.orm.yml, Resources/config/doctrine/MagentoGroupMapping.orm.yml, Resources/sql/mapping_migration.post_schema_update.sql, Resources/sql/mapping_migration.pre_schema_update.sql, UPGRADE.md, spec/Pim/Bundle/MagentoConnectorBundle/Manager/AttributeGroupMappingManagerSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Manager/AttributeMappingManagerSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Manager/CategoryMappingManagerSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Manager/FamilyMappingManagerSpec.php
| New feature?         | Yes
| BC breaks?           | Yes
| Fixed tickets        | MC-206, MC-194
| DB schema updated?   | Yes
| Migration script?    | Yes
=> MC-206: Manage multiple magento environment on a single PIM instance

Resources/config/repositories.yml
| Fixed tickets        | MC-203
=> MC-203: Clean repositories and rm metadata services

Normalizer/CategoryNormalizer.php
| Fixed tickets        | MC-216
=> MC-216: Use end() function on variable, not directly on method.

Processor/AttributeProcessor.php, spec/Pim/Bundle/MagentoConnectorBundle/Processor/AttributeProcessorSpec.php
| Checkstyle issues?*  |  No
| Fixed tickets        | MC-164 (partially)
=> MC-164: phpspec for AttributeProcessor

Writer/ProductWriter.php
| Fixed tickets        | MC-213
=> MC-213: Fix getProductSku() with configurable product creation

Resources/config/batch_jobs.yml, Resources/fixtures/demo_magento/jobs.yml, Resources/translations/messages.fr.yml
| Bug fix?             | N
| New feature?         | N
| BC breaks?           | N
| Tests pass?          | Y
| Changelog updated?   | Y
| Fixed tickets        | MC-215
| DB schema updated?   | N/A
| Migration script?    | N/A
| Doc PR               | N/A
=> MC-215: Remove full products export job

CHANGELOG.md, Filter/ExportableLocaleFilter.php, Guesser/NormalizerGuesser.php, Normalizer/ProductNormalizer.php, Resources/config/filters.yml, Resources/config/guessers.yml, spec/Pim/Bundle/MagentoConnectorBundle/Filter/ExportableLocaleFilterSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Guesser/NormalizerGuesserSpec.php, spec/Pim/Bundle/MagentoConnectorBundle/Normalizer/ProductNormalizer16Spec.php, spec/Pim/Bundle/MagentoConnectorBundle/Normalizer/ProductNormalizerSpec.php
| Bug fix?             | YES
| BC breaks?           | YES
| Changelog updated?   | YES
| Fixed tickets        | MC-217
=> MC-217: Connector send products only with complete locales

spec/Pim/Bundle/MagentoConnectorBundle/Filter/ExportableProductFilterSpec.php
| Fixed tickets        | MC-214
=> MC-214: Add spec for ExportableProductFilter

CHANGELOG.md, Normalizer/CategoryNormalizer.php
| Tests pass?          | No
| Fixed tickets        | MC-222
=> MC-222: Prevent empty url_key field in normalized category

Reader/ORM/DeltaProductAssociationReader.php
| Fixed tickets        | MC-224
=> MC-224: Fix Delta association export

Normalizer/CategoryNormalizer.php, spec/Pim/Bundle/MagentoConnectorBundle/Normalizer/CategoryNormalizerSpec.php
| Checkstyle issues?*  |  No
| Fixed tickets        | MC-222
=> MC-222: Prevent the generation of an empty url key

CHANGELOG.md, Webservice/WebserviceEE.php
| Fixed tickets        | MC-225
=> MC-225: Prevent an error with url key during product update on Magento EE

CHANGELOG.md, Processor/ConfigurableProcessor.php
| Fixed tickets        | MC-226
| DB schema updated?   | Np
=> MC-226: Fix PHP notice about pimGrouped

README.md
| Checkstyle issues?*  |  N/A
| Changelog updated?   |  No
| Fixed tickets        | MC-227
| DB schema updated?   |  No
| Doc PR               | Yes
=> MC-227: Enhance documentation on bubble api need for configurable products

DependencyInjection/PimMagentoConnectorExtension.php, EventSubscriber/CascadeDeleteDeltaSubscriber.php, Resources/config/event_subscribers.yml, spec/Pim/Bundle/MagentoConnectorBundle/EventSubscriber/CascadeDeleteDeltaSubscriberSpec.php
| Bug fix?             | N
| New feature?         | N
| BC breaks?           | N
| Checkstyle issues?*  | N
| PMD issues?**        | N
| Changelog updated?   | N/A
| Fixed tickets        | MC-219
| DB schema updated?   | N/A
| Migration script?    | N/A
| Doc PR               | N/A
=> MC-219: Add cascade delete subcriber on product deletion

CHANGELOG.md, Webservice/WebserviceEE.php
| Fixed tickets        | MC-228
=> MC-228: Remove url key from product updates with Magento EE

Reader/ORM/DeltaConfigurableReader.php, Reader/ORM/DeltaProductAssociationReader.php, Reader/ORM/DeltaProductReader.php
| Fixed tickets        | MC-230
=> MC-230: Fix bug with multi export in ORM

CHANGELOG.md, Resources/translations/messages.en.yml, Resources/translations/messages.fr.yml
| New feature?         | Yes
| BC breaks?           | Yes
| Fixed tickets        | MC-231
=> MC-231: Add job titles translations

README.md, Resources/doc/userguide.md
| Fixed tickets        | MC-174
| Doc PR               | y
=> MC-174: Improve documentation in readme

Resources/translations/messages.ja.yml
Hi,
I updated locale for Japanese. Please merge.
=> add locales on japanese.

Resources/translations/messages.ja.yml
=> Fix japanese translation

Reader/MongoDBODM/DeltaConfigurableReader.php, Reader/MongoDBODM/DeltaProductAssociationReader.php, Reader/MongoDBODM/DeltaProductReader.php
| Fixed tickets        | MC-233
=> MC-233: Fix configurable and association delta in Mongo

Resources/translations/messages.en.yml, Resources/translations/messages.fr.yml
| Fixed tickets        | MC-231
=> MC-231: Fix translation in job edit page

README.md
| Tests pass?          | n
| Changelog updated?  | n
| Fixed tickets        | 
| Doc PR               | y
=> 1.2: Update readme

CHANGELOG.md, DependencyInjection/PimMagentoConnectorExtension.php
| Changelog updated?   | y
| Fixed tickets        | #464 
=> Fix install mongo #464

CHANGELOG.md, DependencyInjection/PimMagentoConnectorExtension.php
| Changelog updated?   | y
| Fixed tickets        | #464 
=> 460: Fix storage driver getter

Resources/doc/userguide.md
| Fixed tickets        | MC-248
| Doc PR               | Yes
=> MC-248: Products must be complete and active to be exported

Processor/ProductAssociationProcessor.php, README.md, Resources/doc/userguide.md, spec/Pim/Bundle/MagentoConnectorBundle/Processor/ProductAssociationProcessorSpec.php
* Check if associated product is complete and enable
* Create product association when SKU is full number
=> MC-249: Correct product association
